#!/bin/sh

if [ $# -lt 2 ]; then
	cat >&2 <<-EOF
	Usage: $0 <fake_spec> <command> [args]

	fake_spec := "@YYYY-MM-DD hh-mm-ss" | "[+-]<count>[smhdy]"

EOF
	exit 1
fi

case `uname -s` in
	Darwin)
	if [ -n "$DYLD_INSERT_LIBRARIES" ]; then
		DYLD_INSERT_LIBRARIES=libfaketime.dylib:$DYLD_INSERT_LIBRARIES
	else
		DYLD_INSERT_LIBRARIES=libfaketime.dylib
	fi
	DYLD_FORCE_FLAT_NAMESPACE=1
	export DYLD_INSERT_LIBRARIES DYLD_FORCE_FLAT_NAMESPACE
	;;
	*)
	if [ -n "$LD_PRELOAD" ]; then
		LD_PRELOAD=libfaketime.so:$LD_PRELOAD
	else
		LD_PRELOAD=libfaketime.so
	fi
	export LD_PRELOAD
	;;
esac

FAKETIME=$1
export FAKETIME
shift

"$@"
